spring.application.name=jp-capacitacao-guilherme-antonio-silva

# Oracle
spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@localhost:1521:XE}
spring.datasource.username=${ORACLE_USERNAME}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate

#Use ddl-auto=validate apenas se o banco de dados estiver OK,
# caso a aplicação não esteja executando coloque em ddl-auto=none ou ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Logs (Pra ver as queries)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true